export const OriginalHolidayData = [
    { id: 1, city: "Paris", country: "France", price: 1200, deal: true, rating: 4.5, duration: "7 days", imageUrl: "https://dynl.mktgcdn.com/p/N2BB4ohwclor2uLoZ7XMHgJmxOZaMOokMdQqqXQAq3s/500x500", description: "The city of love and lights, home to the iconic Eiffel Tower and Louvre Museum.", tags: ["culture", "history", "nightlife"] },
    { id: 2, city: "Tokyo", country: "Japan", price: 1500, deal: false, rating: 4.8, duration: "5 days", imageUrl: "https://a.mktgcdn.com/p/5y1rccQEtZvLCa6Jj2O56is_Qrn1ItZ3nxsNpdsvYlM/3000x2000.jpg", description: "A bustling metropolis blending the ultra-modern with traditional temples and cherry blossoms.", tags: ["modern", "culture", "adventure"] },
    { id: 3, city: "Cairo", country: "Egypt", price: 900, deal: true, rating: 4.2, duration: "10 days", imageUrl: "https://media.tacdn.com/media/attractions-splice-spp-674x446/0c/0d/cb/21.jpg", description: "The heart of ancient civilization, featuring the Great Pyramids of Giza and the Sphinx.", tags: ["history", "culture"] },
    { id: 4, city: "New York", country: "USA", price: 1300, deal: false, rating: 4.7, duration: "6 days", imageUrl: "https://image.cnbcfm.com/api/v1/image/106268734-1574876711571gettyimages-1059614218.jpeg?v=1576856860", description: "The city that never sleeps, offering iconic landmarks like the Statue of Liberty and Times Square.", tags: ["modern", "nightlife"] },
    { id: 5, city: "Sydney", country: "Australia", price: 1700, deal: true, rating: 4.9, duration: "8 days", imageUrl: "https://media.tatler.com/photos/6141d37b9ce9874a3e40107d/16:9/w_2560%2Cc_limit/social_crop_sydney_opera_house_gettyimages-869714270.jpg", description: "Famous for its Opera House and Harbour Bridge, Sydney offers stunning beaches and vibrant culture.", tags: ["beach", "culture", "adventure"] },
    { id: 6, city: "Rome", country: "Italy", price: 1100, deal: false, rating: 4.6, duration: "7 days", imageUrl: "https://miro.medium.com/v2/resize:fit:1400/1*gfzxEKbwzFDI8L-h2FQSrw.jpeg", description: "The Eternal City, rich in history with its ancient ruins, the Vatican, and mouthwatering cuisine.", tags: ["history", "culture", "relaxation"] },
    { id: 7, city: "London", country: "UK", price: 1400, deal: true, rating: 4.4, duration: "4 days", imageUrl: "https://lp-cms-production.imgix.net/2019-06/b9a6b2f5d01762c24e2309ec37fb80a9-big-ben.jpg", description: "A city of contrasts, offering historic sites like the Tower of London alongside modern attractions.", tags: ["history", "modern", "culture"] },
    { id: 8, city: "Bangkok", country: "Thailand", price: 80000, deal: false, rating: 4.3, duration: "9 days", imageUrl: "https://content.r9cdn.net/rimg/dimg/26/5b/01e97574-city-26166-1592813274a.jpg?width=1366&height=768&xhint=1038&yhint=725&crop=true", description: "A vibrant city known for its ornate shrines, vibrant street life, and the opulent Grand Palace.", tags: ["culture", "adventure", "nightlife"] },
    { id: 9, city: "Dubai", country: "UAE", price: 2000, deal: true, rating: 4.8, duration: "5 days", imageUrl: "https://content.r9cdn.net/rimg/dimg/9c/5d/375edbe5-city-6080-166f9a95b45.jpg?width=1366&height=768&xhint=3688&yhint=2622&crop=true", description: "A futuristic city with skyscrapers, luxury shopping, and a lively nightlife scene.", tags: ["modern", "shopping", "nightlife"] },
    { id: 10, city: "Cancun", country: "Mexico", price: 950, deal: false, rating: 4.7, duration: "7 days", imageUrl: "https://destinationlesstravel.com/wp-content/uploads/2022/05/Birds-eye-view-of-the-Cancun-Hotel-zone-on-a-beautiful-day.jpg", description: "Known for its beaches, numerous resorts, and nightlife, Cancun is part of the Riviera Maya.", tags: ["beach", "relaxation", "nightlife"] }
  ];